### ISSUE TITLE
Checkout to other users

### ISSUE THREAD

**Issue by CallumWalton** [paul1278/snipe-it-kiosk#20]
Hey paul1278,

Awesome application; just started using it. Would be awesome to check out to other users.

**Comment by CallumWalton** [comment]
Managed to implement this feature; will provide merge request soon :)

**Comment by paul1278** [comment]
Hey, very nice that youre using this project! :D Thank you, will take a look at your changes as soon as you start the PR.

**Comment by CallumWalton** [comment]
Hey no worries, thank you!
